version: '3.7'

services:
  app_node:
    build:
      context: .
      target: development
    command: 'npx nodemon server/server.js -e json,hbs,html,css,map,js'
    ports:
      - '3000:3000'
    volumes:
      - '.:/srv/src'
      - 'node_modules:/srv/src/node_modules'

volumes:
  node_modules:
    driver: local
